### ISSUE TITLE
DBデータ -> 欲しい形式に加工

### ISSUE THREAD

**Issue by kathmandu777** [MURATA-Laboratory/seminar-2022-newline-model#1]

**Comment by tnkryoga** [comment]
やること
・CSVファイルの形にデータを加工する
　→　[https://work-life-enj.com/pyhon-write-csv/](url)
・データの整形にはnumpyがよさそう
・データの加工はSQLでDBからデータを抽出する

**Comment by tnkryoga** [comment]
多分ローカル上ではできた
形式は
1列目：前文節[SEP]現在の文節
2列目：改行するかしないかのフラグ
3列目：読点挿入するかどうかのフラグ
